/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

import javax.swing.JOptionPane;

/**
 *
 * @author mxD
 */
public class ForgotNoRekening extends javax.swing.JFrame {

    /**
     * Creates new form ForgotNoRekening
     */
    Kel5Database db = new Kel5Database();
    
    private int xMouse, yMouse;
    
    public ForgotNoRekening() {
        super("Forgot Nomor Rekening");
        initComponents();
        this.setSize(535, 275);
        setLocationRelativeTo(null);
        noRekText.setVisible(false);
        getNoRek.setVisible(false);
        gotoLogin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        noRekText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nextB = new javax.swing.JButton();
        getNoRek = new javax.swing.JLabel();
        gotoLogin = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        frameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Masukkan email anda untuk mendapatkan nomor rekening");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 380, 30);

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailField.setToolTipText("Nomor Rekening");
        getContentPane().add(emailField);
        emailField.setBounds(170, 30, 180, 30);

        noRekText.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        noRekText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noRekText.setText("Nomor Rekening Anda");
        getContentPane().add(noRekText);
        noRekText.setBounds(160, 90, 200, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/Kel5BankLogo_Small.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 170, 60, 60);

        nextB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nextB.setText("NEXT");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });
        getContentPane().add(nextB);
        nextB.setBounds(220, 160, 70, 23);

        getNoRek.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        getNoRek.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getNoRek.setText("000000");
        getContentPane().add(getNoRek);
        getNoRek.setBounds(200, 110, 120, 40);

        gotoLogin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        gotoLogin.setText("Go to Login");
        gotoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(gotoLogin);
        gotoLogin.setBounds(190, 160, 130, 23);

        backB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        backB.setText("BACK");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB);
        backB.setBounds(220, 190, 70, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/sky-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-100, -10, 700, 450);

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        getContentPane().add(frameDrag);
        frameDrag.setBounds(0, 0, 520, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
        // Action Button

        String email = emailField.getText();
        
        if(emailField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Tolong isi email anda :)");
            emailField.requestFocus();
        }
        else
        {
            db.forgotNoRek(email);
            
            if (db.getU() > 0)
            {
                noRekText.setVisible(true);
                getNoRek.setVisible(true);
                gotoLogin.setVisible(true);
                nextB.setVisible(false);

                getNoRek.setText(String.valueOf(db.getNoRekening()));
            }
        }
    }//GEN-LAST:event_nextBActionPerformed

    private void gotoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoLoginActionPerformed
        // TODO add your handling code here:
        
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gotoLoginActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // back to login form action button

        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        // TODO add your handling code here:

        int x, y;

        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotNoRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotNoRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotNoRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotNoRekening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotNoRekening().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel getNoRek;
    private javax.swing.JButton gotoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton nextB;
    private javax.swing.JLabel noRekText;
    // End of variables declaration//GEN-END:variables
}
