/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
   * and open the template in the editor.
 */

package bankPBO;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.Timer;

/**
 *
 * @author rafixsz
 */
public class Loading extends javax.swing.JFrame {
private Timer t = null;
private int count = 0;
    /**
     * Creates new form Loading
     */
    public Loading() {
        super("Aplikasi Bank PBO kelompok 5");
        initComponents();
        this.setSize(568, 400);
        this.setLocationRelativeTo(null);
        
        playSound();
        
        t = new Timer(45, new ActionListener(){
            
        @Override
        public void actionPerformed(ActionEvent e)
        {
            count ++;
            jProgressBar1.setValue(count);
            if(jProgressBar1.getValue() < 100)
            {
                jProgressBar1.setValue(jProgressBar1.getValue()+1);
            }
            else
            {
                t.stop();
                dispose();
                new LoginForm().setVisible(true);
            }
        }
        });
        t.start();
    }
    
    public void playSound() {
   
        try 
        {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("G:\\java_netbeans\\tugasAkhir_Kel5\\src\\openingSrc\\LOGO.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch(Exception ex)   
        {
                System.out.println("Error with playing sound.");
                ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(jProgressBar1);
        jProgressBar1.setBounds(-10, 380, 580, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/Kel5BankLogo_11.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(90, 220, 200, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/ubm_logo2.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 250, 180, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/sky-bg.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(-40, -60, 630, 520);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 570, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
