/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author mxD
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    Kel5Database db = new Kel5Database();
    protected static int noRek, pin;
    
    private int xMouse, yMouse;
    
    public LoginForm() {
        super("Aplikasi Bank PBO Kelompok 5");
        initComponents();
        this.setSize(520, 220);
        setLocationRelativeTo(null);
        
        noRekField.requestFocus();
        
        currentDate();
    }
    
    public void currentDate()
    {
        Thread clock = new Thread(){
            public void run(){
                    while (true){
                        Calendar cal = Calendar.getInstance();
                        int date = cal.get(Calendar.DAY_OF_MONTH);
                        int month = cal.get(Calendar.MONTH);
                        int year = cal.get(Calendar.YEAR);

                        int hour;
                        int minute;
                        int second;

                        dateText.setText(date + "/" + (month+1) + "/" + year);

                        hour = cal.get(Calendar.HOUR);
                        minute = cal.get(Calendar.MINUTE);
                        second = cal.get(Calendar.SECOND);

                        timeText.setText(hour + ":" + minute + ":" + second);
                    }
                }
        };
        
        clock.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        noRekField = new javax.swing.JTextField();
        loginB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        forgotPinB = new javax.swing.JButton();
        registerB = new javax.swing.JButton();
        forgotNoRekB = new javax.swing.JButton();
        dateText = new javax.swing.JLabel();
        timeText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        minimizeWindows = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        frameDrag = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("No. Rekening");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 40, 120, 30);
        jPanel1.add(pinField);
        pinField.setBounds(300, 80, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 80, 80, 30);

        noRekField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noRekField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRekFieldActionPerformed(evt);
            }
        });
        jPanel1.add(noRekField);
        noRekField.setBounds(300, 40, 200, 30);

        loginB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginB.setText("Log In");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        loginB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginBKeyPressed(evt);
            }
        });
        jPanel1.add(loginB);
        loginB.setBounds(300, 120, 67, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/Kel5BankLogo.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 170, 160);

        forgotPinB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        forgotPinB.setText("Forgot PIN");
        forgotPinB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPinBActionPerformed(evt);
            }
        });
        jPanel1.add(forgotPinB);
        forgotPinB.setBounds(300, 150, 200, 23);

        registerB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        registerB.setText("Register");
        registerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBActionPerformed(evt);
            }
        });
        jPanel1.add(registerB);
        registerB.setBounds(420, 120, 80, 23);

        forgotNoRekB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        forgotNoRekB.setText("Forgot Nomor Rekening");
        forgotNoRekB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotNoRekBActionPerformed(evt);
            }
        });
        jPanel1.add(forgotNoRekB);
        forgotNoRekB.setBounds(300, 180, 200, 23);

        dateText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dateText.setText("00/00/0000");
        jPanel1.add(dateText);
        dateText.setBounds(50, 190, 70, 15);

        timeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        timeText.setText("00 : 00");
        jPanel1.add(timeText);
        timeText.setBounds(50, 170, 50, 15);

        jLabel8.setText("DATE :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 190, 34, 14);

        jLabel9.setText("TIME :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 170, 31, 14);

        minimizeWindows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/minimize2.png"))); // NOI18N
        minimizeWindows.setContentAreaFilled(false);
        minimizeWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeWindowsActionPerformed(evt);
            }
        });
        jPanel1.add(minimizeWindows);
        minimizeWindows.setBounds(460, 0, 30, 20);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/closeApp2.png"))); // NOI18N
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(493, 0, 30, 20);

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel1.add(frameDrag);
        frameDrag.setBounds(0, 0, 520, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/moneyBackgroundTexture.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 520, 220);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        // login action button
        
        // isi no rekening
        try
        {
            noRek = Integer.parseInt(noRekField.getText());
            noRekField.requestFocus();
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "no rekeing tidak boleh kosong\n-----------------------\ndan harus berupa angka");
        }
        
        // isi pin
        try
        {
            pin = Integer.parseInt(String.valueOf(pinField.getPassword()));
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "pin tidak boleh kosong\n-----------------------\ndan harus berupa angka");
            pinField.requestFocus();
        }
        
        if (noRek > 0 && pin > 0)
        {
            db.preIn(noRek, pin);
            
            if (db.u > 0)
            {
                this.dispose();
            }
        }
    }//GEN-LAST:event_loginBActionPerformed

    private void registerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBActionPerformed
        // register button action
        
        this.dispose();
        new RegisForm().setVisible(true);
    }//GEN-LAST:event_registerBActionPerformed

    private void forgotPinBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPinBActionPerformed
        // password resetter
        
        this.dispose();
        new ForgotPin().setVisible(true);
        
    }//GEN-LAST:event_forgotPinBActionPerformed

    private void forgotNoRekBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotNoRekBActionPerformed
        // TODO add your handling code here:
        
        new ForgotNoRekening().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_forgotNoRekBActionPerformed

    private void noRekFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRekFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRekFieldActionPerformed

    private void loginBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBKeyPressed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(1);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void minimizeWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeWindowsActionPerformed
        // TODO add your handling code here:
        
        this.setState(LoginForm.ICONIFIED);
    }//GEN-LAST:event_minimizeWindowsActionPerformed

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        // TODO add your handling code here:
        
        int x, y;
        
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        // TODO add your handling code here:
        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateText;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton forgotNoRekB;
    private javax.swing.JButton forgotPinB;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginB;
    private javax.swing.JButton minimizeWindows;
    private javax.swing.JTextField noRekField;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JButton registerB;
    private javax.swing.JLabel timeText;
    // End of variables declaration//GEN-END:variables
}
