/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

import javax.swing.JOptionPane;

/**
 *
 * @author mxD
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    
    Kel5Database db = new Kel5Database();
    String getTxt = null, nom = null;
    int hargaByr = 0;
    
    public Pembayaran() {
        initComponents();
        this.setSize(500, 310);
        this.setLocationRelativeTo(null);
        
        nomorHpTxt.setVisible(false);
        nomField.setVisible(false);
        
        tokenListrikTxt.setVisible(false);
        nomField.setVisible(false);
        
        nominal.setVisible(false);
        prosesB.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pilihPembayaran = new javax.swing.JComboBox<>();
        nominal = new javax.swing.JComboBox<>();
        tokenListrikTxt = new javax.swing.JLabel();
        nomorHpTxt = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        nextB = new javax.swing.JButton();
        prosesB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setLayout(null);

        pilihPembayaran.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        pilihPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Pembayaran", "Listrik", "Pulsa HP" }));
        jPanel2.add(pilihPembayaran);
        pilihPembayaran.setBounds(10, 10, 180, 30);

        nominal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah Nominal", "1) Rp. 25.000", "2) Rp. 50.000", "3) Rp. 100.000", "4) Rp. 200.000", " " }));
        jPanel2.add(nominal);
        nominal.setBounds(340, 170, 140, 30);

        tokenListrikTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tokenListrikTxt.setForeground(new java.awt.Color(255, 255, 255));
        tokenListrikTxt.setText("Masukkan Token Listrik Anda :");
        jPanel2.add(tokenListrikTxt);
        tokenListrikTxt.setBounds(10, 130, 250, 30);

        nomorHpTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nomorHpTxt.setForeground(new java.awt.Color(255, 255, 255));
        nomorHpTxt.setText("Masukkan Nomor Hp Anda :");
        jPanel2.add(nomorHpTxt);
        nomorHpTxt.setBounds(10, 130, 250, 30);

        nomField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(nomField);
        nomField.setBounds(10, 170, 240, 30);

        nextB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nextB.setText("Next");
        nextB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBActionPerformed(evt);
            }
        });
        jPanel2.add(nextB);
        nextB.setBounds(210, 10, 73, 30);

        prosesB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        prosesB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/checker5.png"))); // NOI18N
        prosesB.setContentAreaFilled(false);
        prosesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBActionPerformed(evt);
            }
        });
        jPanel2.add(prosesB);
        prosesB.setBounds(160, 250, 80, 50);

        cancelB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/cancel4.png"))); // NOI18N
        cancelB.setContentAreaFilled(false);
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });
        jPanel2.add(cancelB);
        cancelB.setBounds(10, 250, 70, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/paymentBG2.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBActionPerformed
        // TODO add your handling code here:
        
        getTxt = String.valueOf(pilihPembayaran.getSelectedItem());
        
        switch (getTxt) {
            case "Listrik":
                tokenListrikTxt.setVisible(true);
                nomField.setVisible(true);
                nomorHpTxt.setVisible(false);
                nominal.setVisible(true);
                prosesB.setVisible(true);
                break;
            case "Pulsa HP":
                nomorHpTxt.setVisible(true);
                nomField.setVisible(true);
                tokenListrikTxt.setVisible(false);
                nominal.setVisible(true);
                prosesB.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Silahkan pilih pembayaran anda");
                break;
        }
    }//GEN-LAST:event_nextBActionPerformed

    private void prosesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBActionPerformed
        // TODO add your handling code here:
        
        int uu = 0;
        
        nom = nomField.getText();

        if(nomField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Maaf, field tidak boleh kosong");
        }
        else
        {
            if (nom.length() < 11)
            {
                JOptionPane.showMessageDialog(null, "Maaf, nomor input anda kurang dari batas\nsilahkan dicek kembali");
            }
            else if (nom.length() > 12)
            {
                JOptionPane.showMessageDialog(null, "Maaf, nomor input anda melebihi batas\nsilahkan dicek kembali");
            }
            else
            {
                uu++;
            }
        }
        
        
        String getNominal = String.valueOf(nominal.getSelectedItem());
        switch (getNominal) {
            case "1) Rp. 25.000":
                hargaByr = 25000;
                break;
            case "2) Rp. 50.000":
                hargaByr = 50000;
                break;
            case "3) Rp. 100.000":
                hargaByr = 100000;
                break;
            case "4) Rp. 200.000":
                hargaByr = 200000;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Tolong pilih jumlah nominal yang ingin dibeli");
                break;
        }
        
        if(!nomField.getText().equals("") && hargaByr != 0 && uu > 0)
        {
            db.inputPembayaran(String.valueOf(LoginForm.noRek), nom, hargaByr, getTxt);
            this.dispose();
        }
        
        System.out.println(nom);
        
    }//GEN-LAST:event_prosesBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nextB;
    private javax.swing.JTextField nomField;
    private javax.swing.JComboBox<String> nominal;
    private javax.swing.JLabel nomorHpTxt;
    private javax.swing.JComboBox<String> pilihPembayaran;
    private javax.swing.JButton prosesB;
    private javax.swing.JLabel tokenListrikTxt;
    // End of variables declaration//GEN-END:variables
}
