/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

//import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/** 
 *
 * @author mxD
 */
public class RegisForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisForm
     */
    
    Kel5Database db = new Kel5Database();
    
    private String name = null, email = null, alamat = null, qKeamanan = null;
    private int pin = 0;
    
    private int xMouse, yMouse;
    
    public RegisForm() {
        super("Registrasi akun bank_pbo kita :)");
        initComponents();
        this.setSize(350, 500);
        this.setLocationRelativeTo(null);
        newNoRek.setText(String.valueOf(db.getNoRekDaft()));
        
        nameField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressField = new javax.swing.JTextArea();
        regisB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        newPinField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        newNoRek = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        minimizeWindows = new javax.swing.JButton();
        frameDrag = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(155, 138, 0, 0);

        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/Kel5BankLogo_11.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 0, 200, 110);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 110, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("PIN baru");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 220, 80, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 270, 50, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("E-Mail");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 170, 50, 17);

        nameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameField.setToolTipText("");
        jPanel1.add(nameField);
        nameField.setBounds(20, 140, 310, 21);

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(emailField);
        emailField.setBounds(20, 190, 310, 21);

        addressField.setColumns(20);
        addressField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addressField.setRows(5);
        jScrollPane1.setViewportView(addressField);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 310, 81);

        regisB.setText("Register");
        regisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisBActionPerformed(evt);
            }
        });
        jPanel1.add(regisB);
        regisB.setBounds(30, 430, 290, 23);

        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        jPanel1.add(backB);
        backB.setBounds(30, 460, 290, 23);

        newPinField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(newPinField);
        newPinField.setBounds(20, 240, 310, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("No Rekening Anda : ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 390, 120, 14);

        newNoRek.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        newNoRek.setForeground(new java.awt.Color(255, 255, 255));
        newNoRek.setText("00000");
        jPanel1.add(newNoRek);
        newNoRek.setBounds(120, 380, 80, 30);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/closeApp2.png"))); // NOI18N
        exitButton.setContentAreaFilled(false);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton);
        exitButton.setBounds(320, 0, 30, 20);

        minimizeWindows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/minimize2.png"))); // NOI18N
        minimizeWindows.setContentAreaFilled(false);
        minimizeWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeWindowsActionPerformed(evt);
            }
        });
        jPanel1.add(minimizeWindows);
        minimizeWindows.setBounds(290, 0, 30, 20);

        frameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                frameDragMouseDragged(evt);
            }
        });
        frameDrag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                frameDragMousePressed(evt);
            }
        });
        jPanel1.add(frameDrag);
        frameDrag.setBounds(0, 0, 350, 500);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/regisBg2.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -60, 350, 580);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 350, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisBActionPerformed
        // register button action
        
        if (nameField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Harap isi nama anda :)");
            nameField.requestFocus();
        }
        else
        {
            name = nameField.getText();
        }
        
        if (emailField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Harap isi email anda");
            emailField.requestFocus();
        }
        else
        {
            email = emailField.getText();
        }
        
        if (addressField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Harap isi alamat anda");
            addressField.requestFocus();
        }
        else
        {
            alamat = addressField.getText();
        }
        
        try
        {
            pin = Integer.parseInt(String.valueOf(newPinField.getPassword()));
            
            if(String.valueOf(pin).length() > 5)
            {
                JOptionPane.showMessageDialog(null, "PIN tidak boleh lebih dari 5 ANGKA");
            }
            else
            {
                if (name != null && email != null && alamat != null)
                {
                    JOptionPane.showMessageDialog(null, "Demi keamanan anda, tolong isi kata kunci keamanan anda\nDAN TOLONG DI INGAT :)");
                    qKeamanan = JOptionPane.showInputDialog(null, "Masukkan kata kunci keamanan anda\nContoh : jakarta, kucing, jambi, milky !!");

                    if (qKeamanan.equals(""))
                    {
                        JOptionPane.showMessageDialog(null, "Tolong isi pertanyaan keamanan anda");
                    }
                    else
                    {
                        int confirm = JOptionPane.showOptionDialog(null, "Pastikan anda ingat nomor rekeing anda\nNomor REKEING ANDA :\n" + db.getNoRekDaft(), "Confirm Option", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

                        if (confirm == JOptionPane.YES_OPTION)
                        {
                            db.prePreIn(pin, name, email, alamat, qKeamanan);
                            this.dispose();
                            new LoginForm().setVisible(true);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Please check nomor rekeing anda di bawah kota box ALAMAT");
                        }
                    }
                }
            }
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Harap isi pin dengan ANGKA");
        }
    }//GEN-LAST:event_regisBActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // back to login form action button
        
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:

        System.exit(1);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void minimizeWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeWindowsActionPerformed
        // TODO add your handling code here:

        this.setState(LoginForm.ICONIFIED);
    }//GEN-LAST:event_minimizeWindowsActionPerformed

    private void frameDragMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMouseDragged
        // TODO add your handling code here:

        int x, y;

        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_frameDragMouseDragged

    private void frameDragMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_frameDragMousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_frameDragMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressField;
    private javax.swing.JButton backB;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel frameDrag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton minimizeWindows;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel newNoRek;
    private javax.swing.JPasswordField newPinField;
    private javax.swing.JButton regisB;
    // End of variables declaration//GEN-END:variables
}
