/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

import javax.swing.JOptionPane;

/**
 *
 * @author mxD
 */
public class TransferForm extends javax.swing.JFrame {

    /**
     * Creates new form TransferForm
     */
    
    Kel5Database db = new Kel5Database();
    protected static int u = 0;
    
    public TransferForm() {
        super("Transfer");
        initComponents();
        this.setSize(450, 300);
        this.setLocationRelativeTo(null);
        //this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rekeningPenerimaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        uangTransferField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        prosesB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MASUKKAN NOMOR REKENING YANG DITUJU");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 410, 40);

        rekeningPenerimaField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        rekeningPenerimaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(rekeningPenerimaField);
        rekeningPenerimaField.setBounds(30, 40, 390, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MASUKKAN JUMLAH UANG YANG INGIN DIKIRIM");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 430, 40);

        uangTransferField.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        uangTransferField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(uangTransferField);
        uangTransferField.setBounds(60, 150, 360, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rp. ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 50, 40);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("*Minimal Transfer Rp. 5000");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 200, 170, 14);

        prosesB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        prosesB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/checker5.png"))); // NOI18N
        prosesB.setToolTipText("DONE!");
        prosesB.setContentAreaFilled(false);
        prosesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesBActionPerformed(evt);
            }
        });
        jPanel1.add(prosesB);
        prosesB.setBounds(300, 220, 70, 60);

        cancelB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cancelB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/cancel4.png"))); // NOI18N
        cancelB.setToolTipText("CANCEL");
        cancelB.setContentAreaFilled(false);
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });
        jPanel1.add(cancelB);
        cancelB.setBounds(70, 230, 60, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/blueNavyBG.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 450, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prosesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesBActionPerformed
        // TODO add your handling code here:
        
        int rekeningPenerima = 0;
        int uangTransfer = 0;
        
        try
        {
            rekeningPenerima = Integer.parseInt(rekeningPenerimaField.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Field nomor rekening tidak boleh kosong");
            rekeningPenerimaField.requestFocus();
        }
        
        try
        {
            uangTransfer = Integer.parseInt(uangTransferField.getText());
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Field uang tidak boleh kosong");
            uangTransferField.requestFocus();
        }
        
        if (rekeningPenerima == LoginForm.noRek)
        {
            JOptionPane.showMessageDialog(null, "Maaf, ini PIN anda. Tolong ulangi :)");
        }
        else
        {
            if (uangTransfer >= 5000)
            {
                db.transfer(rekeningPenerima, uangTransfer);

                if (db.getU() == 3)
                {
                    new  TransferForm1().setVisible(true);
                    this.dispose();
                }
                else
                {
                    rekeningPenerimaField.requestFocus();
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Maaf, minimal transfer uang sebesar\n Rp. 5000");
            }
        }  
        
    }//GEN-LAST:event_prosesBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        u++;
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton prosesB;
    private javax.swing.JTextField rekeningPenerimaField;
    private javax.swing.JTextField uangTransferField;
    // End of variables declaration//GEN-END:variables
}
