/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankPBO;

import javax.swing.JOptionPane;

/**
 *
 * @author mxD
 */
public class TransferForm1 extends javax.swing.JFrame {

    /**
     * Creates new form TransferForm1
     */
    
    Kel5Database db = new Kel5Database();
    
    protected static String tanggalTransfer = UserActivity.date + "/" + (UserActivity.month+1) + "/" + UserActivity.year;
    protected static String waktu = UserActivity.hour + ":" + UserActivity.minute;
    
    public TransferForm1() {
        this.setSize(544, 230);
        this.setLocationRelativeTo(null);
        initComponents();
        
        noRekPenerimaTxt.setText(Kel5Database.namaPenerima);
        namaPenerimaTxt.setText(String.valueOf(Kel5Database.noRekPenerima));
        uangTransferTxt.setText(String.valueOf(Kel5Database.uangKirim));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noRekPenerimaTxt = new javax.swing.JLabel();
        namaPenerimaTxt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        uangTransferTxt = new javax.swing.JLabel();
        kirimB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nomor Rekening Penerima");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 210, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jumlah Uang Transfer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 80, 210, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama penerima");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 210, 40);

        noRekPenerimaTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        noRekPenerimaTxt.setForeground(new java.awt.Color(255, 255, 255));
        noRekPenerimaTxt.setText("xxxxxxxxxxx");
        jPanel1.add(noRekPenerimaTxt);
        noRekPenerimaTxt.setBounds(230, 50, 200, 20);

        namaPenerimaTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namaPenerimaTxt.setForeground(new java.awt.Color(255, 255, 255));
        namaPenerimaTxt.setText("00000");
        jPanel1.add(namaPenerimaTxt);
        namaPenerimaTxt.setBounds(230, 10, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Rp. ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 90, 40, 20);

        uangTransferTxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        uangTransferTxt.setForeground(new java.awt.Color(255, 255, 255));
        uangTransferTxt.setText("000000");
        jPanel1.add(uangTransferTxt);
        uangTransferTxt.setBounds(260, 90, 120, 20);

        kirimB.setText("Kirim");
        kirimB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimBActionPerformed(evt);
            }
        });
        jPanel1.add(kirimB);
        kirimB.setBounds(230, 140, 73, 23);

        cancelB.setText("Cancel");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });
        jPanel1.add(cancelB);
        cancelB.setBounds(230, 170, 73, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/Kel5BankLogo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 10, 190, 180);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSrc/blueNavyBG2.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-6, 0, 550, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kirimBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimBActionPerformed
        // TODO add your handling code here:
        
        db.kirim();
        
        if (db.getU() == 2)
        {
            db.inputTransaksi();
            
            System.out.println(tanggalTransfer + "\n" + waktu);
            JOptionPane.showMessageDialog(null, "Uang telah berhasil dikirim");
            this.dispose();
        }
    }//GEN-LAST:event_kirimBActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_cancelBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferForm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kirimB;
    private javax.swing.JLabel namaPenerimaTxt;
    private javax.swing.JLabel noRekPenerimaTxt;
    private javax.swing.JLabel uangTransferTxt;
    // End of variables declaration//GEN-END:variables
}
